# Generated by Django 4.2.6 on 2023-10-11 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bts',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
